### ISSUE TITLE
Problem Occurred:  Reloading Plugins...' Error reloading plugins

### ISSUE THREAD

**Issue by DojoJoe** [katalon-studio/katalon-studio-basic-report-plugin#15]
On my Win10 (64bit) machine, I installed Katalon v.6.3.2 and the Basic Report plugin with an API key.  Katalon 'Managed Plugins' shows that Basic Report is installed with an API Key. I ran tests, created reports in my project folder on the local drive as expected.  Then I rebooted my computer, and Katalon displays the following error.  Please HELP!! 

Error reloading plugins
com.kms.katalon.plugin.models.ReloadPluginsException: Unexpected error occurs during executing reload plugins under account: credential: xxxxxxxxxx@gmail.com, endpoint: https://store.katalon.com/api/products/ks?appVersion=6.3.2
	at com.kms.katalon.plugin.service.PluginService.reloadPlugins(PluginService.java:189)
	at com.kms.katalon.composer.handlers.ReloadPluginsHandler$1.run(ReloadPluginsHandler.java:61)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.kms.katalon.plugin.models.KStoreClientExceptionWithInfo: Unexpected error occurs during executing get latest plugins
	at com.kms.katalon.plugin.service.KStoreRestClient.getLatestPlugins(KStoreRestClient.java:80)
	at com.kms.katalon.plugin.service.PluginService.fetchLatestPlugins(PluginService.java:201)
	at com.kms.katalon.plugin.service.PluginService.reloadPlugins(PluginService.java:74)
	... 2 more
Caused by: com.kms.katalon.plugin.models.KStoreClientException: Invalid Request. Status Code: 401. Message: Unauthorized
	at com.kms.katalon.plugin.service.KStoreRestClient.executeGetRequest(KStoreRestClient.java:263)
	at com.kms.katalon.plugin.service.KStoreRestClient.getLatestPlugins(KStoreRestClient.java:59)
	... 4 more

**Comment by devalex88** [comment]
Please try again with Katalon Studio 7.0.0.

**Comment by dangparul48** [comment]
Hi @DojoJoe, 
Download the offline basic report plugin from this link: https://github.com/dangparul48/katalon-basic-report-plugin which I just created last night using it's source code already available on Github. Just use this jar in your project to get html and csv reporting back!
